before_install:
  - sudo apt-get install -y maven 
  - sudo add-apt-repository ppa:webupd8team/java
  sudo apt update; sudo apt install -y oracle-java8-installer
  
  language: java
  mvn install
YAML
