CREATE DATABASE library
  WITH
  OWNER = postgres
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.utf8'
  LC_CTYPE = 'en_US.utf8'
  TABLESPACE = pg_default
  CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE library TO postgres;

GRANT TEMPORARY, CONNECT ON DATABASE library TO PUBLIC;

